fn_args_layout = "Vertical"
fn_params_layout = "Tall"
tab_spaces = 2
fn_single_line = true
blank_lines_upper_bound = 8
unstable_features = true
fn_call_width = 80
max_width = 80
indent_style = "Visual"