#fn_args_layout = "Vertical"
fn_params_layout = "Vertical"
tab_spaces = 2
fn_single_line = false
blank_lines_upper_bound = 2
unstable_features = true
fn_call_width = 95
max_width = 95
#indent_style = "Visual"
brace_style = "PreferSameLine"