#fn_args_layout = "Vertical"
fn_params_layout = "Tall"
# brace_style = "PreferSameLine"
fn_single_line = false
unstable_features = true
wrap_comments = true
tab_spaces = 2
blank_lines_upper_bound = 2
comment_width = 80
fn_call_width = 80
max_width = 80
#indent_style = "Visual"

